name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Rodar lint
        run: npm run lint

      - name: Build da aplicação
        run: npm run build

      - name: Rodar testes unitários
        run: npm run test:cov