name: Robot Framework API Tests

on:
  push:
    branches:
      - '*'      # Roda em qualquer branch que receba push
  pull_request:
    branches:
      - '*'      # Roda em qualquer Pull Request
  workflow_dispatch: # Permite rodar manualmente pelo botão no GitHub

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: meu_produto_app
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Agiliza os próximos runs

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências e Preparar Banco
        env:
          DATABASE_URL: "postgresql://postgres:1234@localhost:5433/meu_produto_app?schema=public"
        run: |
          npm install
          npx prisma generate
          npx prisma migrate deploy # <--- Garante que as tabelas existam no container

      - name: Instalar Robot Framework
        run: |
          pip install robotframework robotframework-requests

      - name: Subir API em Background
        env:
          DATABASE_URL: "postgresql://postgres:1234@localhost:5433/meu_produto_app?schema=public"
          JWT_SECRET: "sua_secret_de_teste" # Use a mesma que sua API espera
        run: |
          npm run start &
          # Espera a API responder 200 OK na rota de usuários
          npx wait-on http://localhost:3000/users --timeout 90000 

      - name: Rodar Testes do Robot
        run: npm run test:api

      - name: Upload de Relatórios (Artifacts)
        if: always() # Salva os logs mesmo se o teste falhar
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results
          path: tests/logs/